{
    "chunks": [
        {
            "type": "txt",
            "chunk_number": 1,
            "lines": [
                {
                    "line_number": 1,
                    "text": ""
                },
                {
                    "line_number": 2,
                    "text": "name: Run OS Scraper Daily"
                },
                {
                    "line_number": 3,
                    "text": ""
                },
                {
                    "line_number": 4,
                    "text": "on:"
                },
                {
                    "line_number": 5,
                    "text": "schedule:"
                },
                {
                    "line_number": 6,
                    "text": "- cron: \"0 21 * * *\"  # Every day at 9:00 PM UTC (7:00 AM AEST)"
                },
                {
                    "line_number": 7,
                    "text": "workflow_dispatch:"
                },
                {
                    "line_number": 8,
                    "text": ""
                },
                {
                    "line_number": 9,
                    "text": "jobs:"
                },
                {
                    "line_number": 10,
                    "text": "run-script:"
                },
                {
                    "line_number": 11,
                    "text": "runs-on: ubuntu-latest"
                },
                {
                    "line_number": 12,
                    "text": "steps:"
                },
                {
                    "line_number": 13,
                    "text": "- name: Checkout repository"
                },
                {
                    "line_number": 14,
                    "text": "uses: actions/checkout@v3"
                },
                {
                    "line_number": 15,
                    "text": "with:"
                },
                {
                    "line_number": 16,
                    "text": "fetch-depth: 0"
                },
                {
                    "line_number": 17,
                    "text": "persist-credentials: true"
                },
                {
                    "line_number": 18,
                    "text": ""
                },
                {
                    "line_number": 19,
                    "text": "- name: Set up Python"
                },
                {
                    "line_number": 20,
                    "text": "uses: actions/setup-python@v4"
                },
                {
                    "line_number": 21,
                    "text": "with:"
                },
                {
                    "line_number": 22,
                    "text": "python-version: '3.10'"
                },
                {
                    "line_number": 23,
                    "text": ""
                },
                {
                    "line_number": 24,
                    "text": "- name: Install dependencies"
                },
                {
                    "line_number": 25,
                    "text": "run: pip install pandas requests beautifulsoup4"
                },
                {
                    "line_number": 26,
                    "text": ""
                },
                {
                    "line_number": 27,
                    "text": "- name: Run Python script"
                },
                {
                    "line_number": 28,
                    "text": "run: python os_scraper.py"
                },
                {
                    "line_number": 29,
                    "text": ""
                },
                {
                    "line_number": 30,
                    "text": "- name: Commit and push CSV if it exists"
                },
                {
                    "line_number": 31,
                    "text": "run: |"
                },
                {
                    "line_number": 32,
                    "text": "git config user.name \"laineyyork-esa\""
                },
                {
                    "line_number": 33,
                    "text": "git config user.email \"216996747+laineyyork-esa@users.noreply.github.com\""
                },
                {
                    "line_number": 34,
                    "text": "git fetch origin"
                },
                {
                    "line_number": 35,
                    "text": "git reset --hard origin/main"
                },
                {
                    "line_number": 36,
                    "text": "if [ -f latest_os_versions.csv ]; then"
                },
                {
                    "line_number": 37,
                    "text": "git add latest_os_versions.csv"
                },
                {
                    "line_number": 38,
                    "text": "git diff --quiet latest_os_versions.csv || git commit -m \"Update CSV [auto]\""
                },
                {
                    "line_number": 39,
                    "text": "git push origin main"
                },
                {
                    "line_number": 40,
                    "text": "else"
                },
                {
                    "line_number": 41,
                    "text": "echo \"\u26a0\ufe0f CSV file not found. Skipping commit.\""
                },
                {
                    "line_number": 42,
                    "text": "env:"
                },
                {
                    "line_number": 43,
                    "text": "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
                }
            ],
            "token_count": 281
        }
    ]
}
