name: Run OS Scraper Daily

on:
  schedule:
    - cron: "0 21 * * *"  # Runs daily at 9:00 PM UTC (7:00 AM AEST)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests beautifulsoup4

      - name: Run Python script
        run: python os_scraper.py

        def compile_os_updates():
    all_data = []
    all_data.extend(scrape_apple_releases())
    all_data.extend(fetch_chromebook_schedule())
    all_data.extend(scrape_windows_releases())

    df = pd.DataFrame(all_data)

    # ✅ Fallback: Ensure CSV is created even if no data is scraped
    if df.empty:
        df = pd.DataFrame(columns=["Platform", "Release", "Date", "Checked_On"])

    df["Checked_On"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    df.to_csv("latest_os_versions.csv", index=False)
    print("✅ OS update data saved to latest_os_versions.csv")

      - name: Commit and push CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin
          git reset --hard origin/main
          git add latest_os_versions.csv
          git diff --quiet latest_os_versions.csv || git commit -m "Update CSV [auto]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
