name: Run OS Scraper Daily

on:
  schedule:
    - cron: "0 21 * * *"  # Every day at 9:00 PM UTC (7:00 AM AEST)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests beautifulsoup4

      - name: Run Python script
        run: python os_scraper.py

      - name: Commit and push CSV if it exists
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git fetch origin
    git reset --hard origin/main
    if [ -f latest_os_versions.csv ]; then
      git add latest_os_versions.csv
      git diff --quiet latest_os_versions.csv || git commit -m "Update CSV [auto]"
      git push origin main
    else
      echo "⚠️ CSV file not found. Skipping commit."
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

